trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

jobs:
  - job: snykScan
    displayName: 'Run Snyk Open Source and Code Scans'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
        displayName: 'Use Python 3.x'

      - script: |
          python -m pip install --upgrade pip
          pip install snyk
        displayName: 'Install Snyk CLI'

      - script: |
          export SNYK_TOKEN=$(SNYK_TOKEN)
          snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: $(SNYK_TOKEN)
        displayName: 'Authenticate Snyk'

      - script: |
          snyk test --all-projects
        displayName: 'Run Snyk Open Source Scan'

      - script: |
          snyk code test
        displayName: 'Run Snyk Code Scan'
