# Runs 4 Snyk Products (Code, Open Source, Container, IaC)
# Outputs the results to the pipeline

# Prerequisites:
# - Set a SNYK_TOKEN in the pipelines secrets
# - Install the HTML viewer extension
#   https://marketplace.visualstudio.com/items?itemName=JakubRumpca.azure-pipelines-html-report

steps:
  - checkout: self

  # .. your instructions on building the app or preparing the repository

  # install & prepare snyk
  - script: |
      npm install -g snyk snyk-to-html

      # This OPTIONAL step will configure the Snyk CLI to connect to the EU or AU instance of Snyk.
      # Docs: https://docs.snyk.io/more-info/data-residency-at-snyk#cli-and-ci-pipelines-urls
      
      # snyk config set endpoint='https://app.eu.snyk.io/api'
      # snyk config set endpoint='https://app.au.snyk.io/api'

      snyk auth $(SNYK_TOKEN)

      # explicitly allow scripts to continue if errors occur
      set +e
    displayName: 'snyk install & auth'
  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'Snyk'
      testType: 'app'
      monitorWhen: 'always'
      failOnIssues: true