trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

jobs:
  - job: snykScan
    displayName: 'Run Snyk Open Source and Code Scans'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'Snyk'
        testType: 'app'
        monitorWhen: 'always'
        failOnIssues: true
